Домашнее задание 1 урок
js-tasks-ru/jsbasic-20230428_tecnx pull request #2
Opened 2023-05-03 20:32 UTC by bifurcatum

2023-05-03 20:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-04 09:20 UTC, SinimaWath requested changes

2023-05-04 09:20 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return !!(size && !empty && !space)
Условие можно упростить до: `return name !== null && name.length >= 4 && ...`

2023-05-04 09:20 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if (str === null || str === undefined || str === '') {
Эту проверку можно упростить до: `if (!str)`

2023-05-04 10:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-05 10:18 UTC, SinimaWath approved these changes

2023-05-05 10:19 UTC, merged